name: Generate terraform docs
on: workflow_dispatch
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.PAT }}
      # with:
      #   ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: ./cluster
        # output-file: README.md
        # output-method: inject
        git-push: "true"
    # - name: Commit files
    #   run: |
    #     git status
