name: Generate terraform docs
on: workflow_dispatch
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.PAT }}
      # with:
      #   ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: ./cluster
        # output-file: README.md
        # output-method: inject
        # git-push: "true"
    - name: Configure git
      run: |
        echo "HI" > test.txt
    - name: Add and commit change
      run: |
        # git config user.name ${{ github.actor }}
        # git config user.email ${{ github.actor }}+github@noreply.com
        # git add .
        git status
        git commit -m "chore: deploy ${{ inputs.service }} ${{ github.sha }}"
        git status
        # git push
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: main
        force: true
    # - name: Pushing to the protected branch 'main'
    #   uses: CasperWA/push-protected@v2
    #   with:
    #     token: ${{ secrets.PAT }}
    #     branch: main
    # - name: Configure git
    #   run: |
    #     git status
