name: Generate terraform docs
on: workflow_dispatch
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Configure git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: ./cluster

    # - name: Add and commit change
    #   run: |
    #     echo "HI" > test.txt
    #     git add .
    #     git commit -m "chore: deploy ${{ inputs.service }} ${{ github.sha }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: main
        force: true
